### ISSUE TITLE
Version inconsistency?

### ISSUE THREAD

**Issue by ferbs** [bitovi/syn#169]
Hi, the latest [release of Syn 0.14.0](https://github.com/bitovi/syn/releases/tag/0.14.0) declares its version as "0.12.0" in its package.json
but NPM shows 0.13 as released [a year ago](https://www.npmjs.com/package/syn/v/0.13.0) and a recent commit [3 weeks ago](https://github.com/bitovi/syn/commit/a2bd4719053e0ebbcd654ab5a155266fb30981e7) bumped package.json up to "0.13.0".

Can I look forward to seeing 0.14 on npm soon?

**Comment by chasenlehara** [comment]
@kdillon I’m a little confused how [0.14 is a tagged release on GitHub](https://github.com/bitovi/syn/releases/tag/0.14.0) but it looks like 0.13 should be the latest ([commits on master](https://github.com/bitovi/syn/commits/master)). Any ideas what happened?

**Comment by kdillon** [comment]
I'm going to close this issue now, since it should be fixed by 0.14.1 .

I should note that I had the same problem today. When I first went to draft the release notes, it said that 0.14.1 already existed and that I couldn't overwrite. I'm not sure what is causing it, but after typing 0.14.2, and then replacing it with 0.14.1 again, it allowed the change.
